// @vitest-environment jsdom

import { beforeEach, describe, expect, it } from 'vitest'
import router from './index'

describe('password reset routing', () => {
  beforeEach(async () => {
    localStorage.clear()
    await router.push('/login')
    await router.isReady()
  })

  it('opens the reset form for the query-token link generated by the server', async () => {
    await router.push('/reset-password?token=query-token')

    expect(router.currentRoute.value.name).toBe('ResetPassword')
    expect(router.currentRoute.value.query.token).toBe('query-token')
    expect(router.currentRoute.value.meta.authScreen).toBe(true)
  })

  it('opens the reset form when the token is supplied in the path', async () => {
    await router.push('/reset-password/path-token')

    expect(router.currentRoute.value.name).toBe('ResetPassword')
    expect(router.currentRoute.value.params.token).toBe('path-token')
    expect(router.currentRoute.value.meta.authScreen).toBe(true)
  })
})
